elasticsearch:
  image: elasticsearch:2.1.0
  ports:
    - 9200:9200

kibana:
  image: kibana:4.3.0
  ports:
    - 5601:5601
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch

logstash:
  image: logstash
  links:
    - elasticsearch
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./tracy-logs:/tracy-logs
   - ./logstash.conf:/etc/logstash/conf.d/logstash.conf

