FROM tomcat:8.0.20-jre8
MAINTAINER Joao Vicente <joao.diogo.vicente@gmail.com>
ADD https://github.com/joaovicente/tracy-web-services/releases/download/v0.2.1/tws.war /usr/local/tomcat/webapps
EXPOSE 8080
